// Integration test on the real RP2350 svd: parses the file with ChipFromSVD and checks
// known chip facts (derived peripheral merging, clusters, register/field/enum contents)
// plus generic structural invariants over every peripheral. When a directory of json
// files generated by the svd_converter binary is passed as second argument, each file is
// compared against the in-process parse result.
#include "svd_parser.hpp"

#include <cstdio>
#include <exception>
#include <fstream>
#include <iterator>
#include <pugixml.hpp>
#include <string>
#include <string_view>
#include <vector>

namespace {

int failures = 0;

#define CHECK(cond, msg)                                        \
    do {                                                        \
        if(!(cond)) {                                           \
            std::printf("FAIL: %s (line %d)\n", msg, __LINE__); \
            ++failures;                                         \
        }                                                       \
    } while(0)

Peripheral const* findPeripheral(Chip const&      chip,
                                 std::string_view name) {
    for(auto const& peripheral : chip.peripherals) {
        if(peripheral.name == name) { return &peripheral; }
    }
    return nullptr;
}

Register const* findRegister(std::vector<Register> const& registers,
                             std::string_view             name) {
    for(auto const& reg : registers) {
        if(reg.name == name) { return &reg; }
    }
    return nullptr;
}

Field const* findField(Register const&  reg,
                       std::string_view name) {
    for(auto const& field : reg.fields) {
        if(field.name == name) { return &field; }
    }
    return nullptr;
}

void checkInstances(Chip const&                                  chip,
                    std::string_view                             name,
                    std::vector<std::pair<std::uint64_t,
                                          std::uint64_t>> const& instances) {
    auto const* peripheral = findPeripheral(chip, name);
    CHECK(peripheral != nullptr, "merged peripheral exists");
    if(peripheral == nullptr) { return; }
    CHECK(peripheral->type == RepeatType::cluster, "merged peripheral is cluster");
    CHECK(peripheral->baseAddresses.size() == instances.size(), "merged peripheral instance count");
    if(peripheral->baseAddresses.size() != instances.size()) { return; }
    for(std::size_t i = 0; i < instances.size(); ++i) {
        CHECK(peripheral->baseAddresses[i].index == instances[i].first,
              "merged peripheral instance index");
        CHECK(peripheral->baseAddresses[i].address == instances[i].second,
              "merged peripheral instance address");
    }
}

void testChipFacts(Chip const& chip) {
    CHECK(chip.name == "RP2350", "chip name");
    CHECK(chip.peripherals.size() == 45, "peripheral count");

    // 9 derivedFrom peripherals in the svd collapse into instance tables
    checkInstances(chip,
                   "UART",
                   {
                     {0, 0x40070000},
                     {1, 0x40078000}
    });
    checkInstances(chip,
                   "I2C",
                   {
                     {0, 0x40090000},
                     {1, 0x40098000}
    });
    checkInstances(chip,
                   "SPI",
                   {
                     {0, 0x40080000},
                     {1, 0x40088000}
    });
    checkInstances(chip,
                   "TIMER",
                   {
                     {0, 0x400b0000},
                     {1, 0x400b8000}
    });
    checkInstances(chip,
                   "PLL",
                   {
                     {0, 0x40050000},
                     {1, 0x40058000}
    });
    checkInstances(chip,
                   "PPB",
                   {
                     {0, 0xe0000000},
                     {1, 0xe0020000}
    });
    checkInstances(chip,
                   "SIO",
                   {
                     {0, 0xd0000000},
                     {1, 0xd0020000}
    });
    checkInstances(chip,
                   "PIO",
                   {
                     {0, 0x50200000},
                     {1, 0x50300000},
                     {2, 0x50400000}
    });

    auto const* resets = findPeripheral(chip, "RESETS");
    CHECK(resets != nullptr, "RESETS exists");
    if(resets != nullptr) {
        CHECK(resets->baseAddresses.front().address == 0x40020000, "RESETS base address");
        CHECK(resets->registers.size() == 3, "RESETS register count");
        auto const* reset = findRegister(resets->registers, "RESET");
        CHECK(reset != nullptr, "RESET register exists");
        if(reset != nullptr) {
            CHECK(reset->addressOffset == 0, "RESET offset");
            CHECK(reset->resetValue == 0x1fffffff, "RESET reset value");
            CHECK(reset->fields.size() == 29, "RESET field count");
            CHECK(reset->zeroMask == 0xe0000000, "RESET zeroMask covers unused bits");
            auto const* usbctrl = findField(*reset, "USBCTRL");
            CHECK(usbctrl != nullptr, "USBCTRL field exists");
            if(usbctrl != nullptr) {
                CHECK(usbctrl->startBit == 28 && usbctrl->stopBit == 28, "USBCTRL bit range");
                CHECK(usbctrl->access == Access::readWrite, "USBCTRL access");
                CHECK(usbctrl->resetValue == 1, "USBCTRL reset value");
            }
        }
    }

    // field names carrying the peripheral name as prefix in the svd get it stripped
    auto const* trng = findPeripheral(chip, "TRNG");
    CHECK(trng != nullptr, "TRNG exists");
    if(trng != nullptr) {
        auto const* busy = findRegister(trng->registers, "BUSY");
        CHECK(busy != nullptr, "TRNG BUSY register exists");
        if(busy != nullptr) {
            CHECK(findField(*busy, "BUSY") != nullptr, "TRNG_BUSY field prefix stripped");
        }
    }
    auto const* psm = findPeripheral(chip, "PSM");
    CHECK(psm != nullptr, "PSM exists");
    if(psm != nullptr) {
        auto const* frceOn = findRegister(psm->registers, "FRCE_ON");
        CHECK(frceOn != nullptr, "PSM FRCE_ON register exists");
        if(frceOn != nullptr) {
            CHECK(findField(*frceOn, "READY") != nullptr, "PSM_READY field prefix stripped");
        }
    }

    // 48 pad control registers live in a dim cluster
    auto const* pads = findPeripheral(chip, "PADS_BANK0");
    CHECK(pads != nullptr, "PADS_BANK0 exists");
    if(pads != nullptr) {
        CHECK(pads->registerGroups.size() == 1, "PADS_BANK0 register group count");
        auto const& group = pads->registerGroups.front();
        CHECK(group.name == "GPIO", "GPIO group name");
        CHECK(group.dim == 48, "GPIO group dim");
        CHECK(group.dimIncrement == 4, "GPIO group increment");
        CHECK(group.addressOffset == 4, "GPIO group offset");
        auto const* pad = findRegister(group.registers, "PAD");
        CHECK(pad != nullptr, "PAD register exists");
        if(pad != nullptr) {
            CHECK(pad->resetValue == 0x56, "PAD reset value");
            auto const* drive = findField(*pad, "DRIVE");
            CHECK(drive != nullptr, "DRIVE field exists");
            if(drive != nullptr) {
                CHECK(drive->type == FieldType::enum_, "DRIVE is enum");
                CHECK(drive->startBit == 4 && drive->stopBit == 5, "DRIVE bit range");
                CHECK(drive->resetValue == 1, "DRIVE reset value");
                CHECK(drive->values.size() == 4, "DRIVE enum value count");
                CHECK(drive->values.front().name == "_2mA", "DRIVE enum name sanitized");
            }
        }
    }
}

bool validIdentifier(std::string_view name) {
    if(name.empty()) { return false; }
    if(std::isdigit(static_cast<unsigned char>(name.front())) != 0) { return false; }
    for(auto const character : name) {
        if(std::isalnum(static_cast<unsigned char>(character)) == 0 && character != '_') {
            return false;
        }
    }
    return true;
}

void checkRegisterInvariants(Register const& reg) {
    auto const width = DataTypeSize(reg.dataType);
    CHECK(validIdentifier(reg.name), "register name is valid identifier");
    for(auto const& field : reg.fields) {
        CHECK(validIdentifier(field.name), "field name is valid identifier");
        CHECK(field.startBit <= field.stopBit, "field bit order");
        CHECK(field.stopBit < width, "field fits register width");
        auto const fieldWidth = field.stopBit - field.startBit + 1;
        CHECK(field.resetValue <= maskFromRange(fieldWidth - 1, 0), "field reset value fits");
        for(auto const& value : field.values) {
            CHECK(validIdentifier(value.name), "enum name is valid identifier");
            CHECK(value.value <= maskFromRange(fieldWidth - 1, 0), "enum value fits field");
        }
    }
}

void testInvariants(Chip const& chip) {
    for(auto const& peripheral : chip.peripherals) {
        CHECK(validIdentifier(peripheral.name), "peripheral name is valid identifier");
        CHECK(!peripheral.baseAddresses.empty(), "peripheral has base address");
        for(auto const& reg : peripheral.registers) { checkRegisterInvariants(reg); }
        for(auto const& group : peripheral.registerGroups) {
            CHECK(group.dim != 0, "register group dim not zero");
            for(auto const& reg : group.registers) { checkRegisterInvariants(reg); }
        }
    }
}

void testGeneratedJson(Chip const&        chip,
                       std::string const& jsonDirectory) {
    for(auto const& peripheral : chip.peripherals) {
        auto const    path = jsonDirectory + "/" + peripheral.name + ".json";
        std::ifstream file{path};
        if(!file) {
            std::printf("FAIL: missing generated file %s\n", path.c_str());
            ++failures;
            continue;
        }
        auto const generated = nlohmann::json::parse(file, nullptr, false);
        if(generated.is_discarded()) {
            std::printf("FAIL: invalid json in %s\n", path.c_str());
            ++failures;
            continue;
        }
        if(nlohmann::json(peripheral) != generated) {
            std::printf("FAIL: generated json differs for %s\n", peripheral.name.c_str());
            ++failures;
        }
    }
}

}   // namespace

int main(int                argc,
         char const* const* argv) {
    try {
        if(argc < 2) {
            std::printf("usage: %s svdfile [generated_json_directory]\n", *argv);
            return 1;
        }
        std::string const svdfile = *std::next(argv, 1);

        pugi::xml_document doc;
        if(!doc.load_file(svdfile.c_str())) {
            std::printf("FAIL: could not load %s\n", svdfile.c_str());
            return 1;
        }

        auto const chip = ChipFromSVD(doc.child("device"));

        testChipFacts(chip);
        testInvariants(chip);
        if(argc > 2) { testGeneratedJson(chip, *std::next(argv, 2)); }

        if(failures == 0) {
            std::printf("all tests passed\n");
            return 0;
        }
        std::printf("%d checks failed\n", failures);
        return 1;
    } catch(std::exception const& exception) {
        std::printf("FAIL: caught %s\n", exception.what());
        return 1;
    }
}
